version: '3.4'

services:
  sqs_consumer:
    build:
      context: .
      target: deps
    command: lein test
    environment:
      LOCALSTACK_HOST: localstack
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.12.6
    ports:
      - "4566:4566"
    environment:
      HOSTNAME: "${LOCALSTACK_HOSTNAME:-localstack}"
      HOSTNAME_EXTERNAL: "${LOCALSTACK_HOSTNAME_EXTERNAL:-localstack}"
      DEFAULT_REGION: "eu-west-1"
      SERVICES: "s3,sqs,sns"
